@extends('layouts.shell')

@section('title', 'Manage Students')
@section('nav-center')<span style="font-size:.875rem;font-weight:600;color:var(--text);">Manage Students</span>@endsection
@section('nav-actions')
<a href="{{ route('admin.dashboard') }}" class="btn btn-ghost" title="Dashboard"><i class="fas fa-arrow-left"></i><span class="nav-text-hidden"> Dashboard</span></a>
<form action="{{ route('admin.logout') }}" method="POST" style="margin:0">@csrf<button type="submit" class="btn btn-ghost" title="Logout"><i class="fas fa-sign-out-alt"></i></button></form>
@endsection

@section('head')
<style>
.students-page{max-width:1120px;margin:0 auto;padding:2.5rem 1.25rem 4rem}.students-layout{display:grid;grid-template-columns:minmax(0,1.5fr) minmax(280px,1fr);gap:1.5rem;align-items:start}.students-list,.create-student{background:var(--surface);border:1px solid var(--border);border-radius:var(--radius-xl);box-shadow:var(--shadow-sm)}.students-list{overflow:hidden}.student-row{display:flex;align-items:center;gap:1rem;padding:1rem 1.25rem;border-bottom:1px solid var(--border)}.student-row:last-child{border-bottom:0}.student-avatar{width:42px;height:42px;flex:0 0 42px;border-radius:50%;display:grid;place-items:center;background:var(--color-accent-surface);color:var(--color-accent);font-weight:800}.student-info{flex:1;min-width:0}.student-info strong{display:block;color:var(--text)}.student-info small{color:var(--text-muted);display:block;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.student-actions{display:flex;gap:.4rem}.create-student{padding:1.25rem}.create-student h2{font-size:1.1rem;color:var(--text);margin:0 0 .25rem}.create-student p{font-size:.8rem;color:var(--text-muted);margin:0 0 1.25rem}.field{margin-bottom:1rem}.field-label{display:block;margin-bottom:.35rem}.group-grid{display:grid;grid-template-columns:1fr 1fr;gap:.75rem}@media(max-width:800px){.students-layout{grid-template-columns:1fr}}@media(max-width:560px){.student-row{align-items:flex-start;flex-wrap:wrap}.student-actions{width:100%;padding-left:58px}.nav-text-hidden{display:none}}
</style>
@endsection

@section('content')
<div class="students-page page-fade-in">
    <div style="margin-bottom:2rem"><h1 class="dash-title" style="font-size:1.8rem">Student accounts</h1><p class="dash-subtitle">Create login credentials and keep each learner's profile ready for future resources.</p></div>
    @if(session('success'))<div class="notice notice--success" style="margin-bottom:1.5rem">{{ session('success') }}</div>@endif
    <div class="students-layout">
        <section><h2 class="section-heading" style="margin-top:0">Students ({{ $students->count() }})</h2><div class="students-list">@forelse($students as $student)<div class="student-row"><div class="student-avatar">{{ strtoupper(substr($student->name,0,1)) }}</div><div class="student-info"><strong>{{ $student->name }} @if($student->role === 'inactive_student')<span class="badge-inactive">INACTIVE</span>@endif</strong><small>ID: {{ $student->username }} · {{ $student->college ?: 'College not added' }} · {{ $student->student_group ?: 'Group not added' }}</small></div><div class="student-actions"><form action="{{ route('admin.toggle-student-status',$student->id) }}" method="POST">@csrf<button class="btn btn-ghost" title="Toggle status"><i class="fas fa-{{ $student->role === 'student' ? 'ban' : 'check' }}"></i></button></form><form action="{{ route('admin.delete-student',$student->id) }}" method="POST" onsubmit="return confirm('Delete this student account?')">@csrf @method('DELETE')<button class="btn btn-ghost" style="color:var(--color-danger)" title="Delete"><i class="fas fa-trash"></i></button></form></div></div>@empty<div style="padding:2rem;text-align:center;color:var(--text-muted)">No student accounts yet.</div>@endforelse</div></section>
        <section class="create-student"><h2><i class="fas fa-user-plus" style="color:var(--color-accent)"></i> Create student</h2><p>Share the student ID and password with the learner.</p><form action="{{ route('admin.store-student') }}" method="POST">@csrf<div class="field"><label class="field-label">Full name</label><input class="field-input" name="name" value="{{ old('name') }}" required></div><div class="field"><label class="field-label">Student ID</label><input class="field-input" name="username" value="{{ old('username') }}" required></div><div class="field"><label class="field-label">Password</label><input class="field-input" type="password" name="password" required></div><div class="field"><label class="field-label">Confirm password</label><input class="field-input" type="password" name="password_confirmation" required></div><div class="group-grid"><div class="field"><label class="field-label">College</label><input class="field-input" name="college" value="{{ old('college') }}"></div><div class="field"><label class="field-label">Group</label><select class="field-input" name="student_group"><option value="">Select</option><option>Science</option><option>Arts</option><option>Commerce</option></select></div></div><div class="field"><label class="field-label">Home / address</label><input class="field-input" name="address" value="{{ old('address') }}"></div><div class="group-grid"><div class="field"><label class="field-label">WhatsApp</label><input class="field-input" name="whatsapp" value="{{ old('whatsapp') }}"></div><div class="field"><label class="field-label">Roll / index</label><input class="field-input" name="index_no" value="{{ old('index_no') }}"></div></div><button class="btn btn-primary" style="width:100%"><i class="fas fa-user-plus"></i> Create account</button></form></section>
    </div>
</div>
@endsection
